#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// FORWARD DECLARATIONS


namespace F_MED_Ramirez_Fallback_Skeleton_AnimBlueprint { struct FAnimBlueprintGeneratedConstantData; }

namespace EmberRae_Axe_R_AnimBP_Post { struct FAnimBlueprintGeneratedConstantData; }

namespace NitroFlow_Axe_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace MetalScout_Axe_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace ButtonStyle_Empty { class UButtonStyle_Empty_C; }

namespace VerseMovement_0 { class U_SolarisSignatureFunctionOuter; }

namespace TextStyle_BurbankSmall_S_White { class UTextStyle_BurbankSmall_S_White_C; }

namespace VerseSimulationMetadata_0 { class USimulation; }

namespace GameplayAbilities { struct FServerAbilityRPCBatch; }

namespace Player_PropertiesDebug_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace ButtonStyle_Empty_0 { class UButtonStyle_Empty_C; }

namespace Blueprint_Paper_VIM { struct FAnimBlueprintGeneratedConstantData; }

namespace GoldenGuard_Axe_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace EmberRae_Axe_L_AnimBP_Post { struct FAnimBlueprintGeneratedConstantData; }

namespace Player_Locomotion_Prototype_Template { struct FAnimBlueprintGeneratedConstantData; }

namespace F_MED_HIS_Ramirez_Head_01_AnimBP_Child { struct FAnimBlueprintGeneratedConstantData; }

namespace Fringe_Plank_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Mechanical_Engineer_Female_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace TextStyle_BurbankSmall_S_White_0 { class UTextStyle_BurbankSmall_S_White_C; }

namespace F_Med_Soldier_01_Skeleton_AnimBP { struct FAnimBlueprintGeneratedConstantData; }


namespace VerseFortnite_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
	struct Ftuple_Lagent_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lfort__character_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lvector3_Mrotation_R;
}

namespace EpicGamesTemporary_0
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_Lvector3_Mvector3_R;
	struct Ftuple_Lfloat_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lrotation_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lfloat_Mfloat_Mfloat_R;
	struct Ftuple_Lrotation_Mrotation_R;
}

namespace VerseSimulation_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_Lint_Many_R;
	class USimulation;
	struct Ftuple_L_R;
}

namespace SwimmingAnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace UnrealEngineExperimental_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_Kchar_M_QLevel_Nlog__level_20_3d_20_2e_2e_2e_R;
}

namespace VerseFortniteInternal_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
	struct Ftuple_Lany_Mability__component_R;
	struct Ftuple_Lint_Mint_R;
}

namespace Verse
{
	struct Ftuple_L_Kchar_M_QDuration_Nfloat_20_3d_20_2e_2e_2e_M_QColor_Ncolor_20_3d_20_2e_2e_2e_R;
	struct Ftuple_L_R;
	struct Ftuple_Lfloat_Mfloat_Mfloat_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_Lfloat_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_L_Kchar_M_Kchar_M_5b_Kchar_5dlocalizable__value_R;
	struct Ftuple_L_Kchar_M_Kchar_R;
	struct Ftuple_Lint_Many_R;
	struct Ftuple_Lfloat_Mfloat_R;
	struct Ftuple_Lint_Mint_R;
}

namespace VerseExperimental
{
	struct Ftuple_Lint_Mint_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace RidingPlayerLayerAnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace VerseEngine_0
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_Lcomponent_Many_R;
}

namespace Player_LocomotionPrototype_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Player_DBNO_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Gameplay_FaceSystem_StateMachine_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace VerseGameplayTags_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace Player_FreeFlying_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace MenuScreen_Athena
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace VerseFortniteUI_0
{
	class UUI;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_Kchar_M_Kchar_M_5b_Kchar_5dlocalizable__value_R;
	struct Ftuple_L_R;
}

namespace Player_SkyDiveAndGlide_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace EpicGamesEngine_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace Player_ProceduralAdjustments_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace VerseUI
{
	struct Ftuple_L_R;
	struct Ftuple_L_Kchar_M_Kchar_M_5b_Kchar_5dlocalizable__value_R;
	class U_SolarisSignatureFunctionOuter;
	class UUI;
}

namespace MANG_PatrolLayerAnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace Player_InAir_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace VerseNative_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace VerseNPC_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_Lnavigation__target_M_QReachRadius_Nfloat_20_3d_20_2e_2e_2e_M_QAllowPartialPath_Nlogic_20_3d_20_2e_2e_2e_R;
	struct Ftuple_L_R;
	struct Ftuple_Lfort__inventory__item__asset_Mint_R;
	struct Ftuple_Lvector3_Mfloat_Mfloat_R;
	struct Ftuple_Lagent_Mfloat_Mfloat_R;
	struct Ftuple_Lagent_Mlogic_R;
}

namespace VerseRestricted
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace Player_DBNOCarried_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace Player_ZipLine_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace VGameplayRst_0
{
	struct Ftuple_L_R;
	struct Ftuple_Lfloat_Mfloat_R;
	struct Ftuple_Lvector3_Mvector3_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_Lcomponent_Many_R;
	struct Ftuple_Lrotation_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lvector3_M_Kchar_R;
	struct Ftuple_Lvector3_M_QParams_Nsphere__draw__params_20_3d_20_2e_2e_2e_R;
}

namespace Player_Land_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace VerseArchetypes
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_Kchar_M_QColor_Ncolor_M_QDuration_Nfloat_R;
	struct Ftuple_Lagent_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_L_Kchar_M_QLevel_Nlog__level_20_3d_20_2e_2e_2e_R;
	struct Ftuple_Lnavigation__target_M_QReachRadius_Nfloat_20_3d_20_2e_2e_2e_M_QAllowPartialPath_Nlogic_20_3d_20_2e_2e_2e_R;
	struct Ftuple_Lfort__character_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lvector3_Mvector3_R;
	struct Ftuple_L_Kchar_M_Kchar_R;
	struct Ftuple_Lvector3_Mfloat_Mfloat_R;
	struct Ftuple_L_R;
	struct Ftuple_Lfort__item__descriptor_Mfort__item__tag_R;
	struct Ftuple_L_Kchar_M_QDuration_Nfloat_20_3d_20_2e_2e_2e_M_QColor_Ncolor_20_3d_20_2e_2e_2e_R;
}

namespace Grandma_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace WolfRidingPlayerLayerAnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace VerseAssets_0
{
	struct Ftuple_Lasset_M_Kchar_R;
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace Player_TacticalState_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Player_Sprint_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace VersePlayspace_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace VerseBasicGameplay
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_Lvector3_M_Kchar_R;
}

namespace Player_LocomotionAdditives_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace GrindRail_Player_LayerAnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Player_Goop_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace CompanionAI_0
{
	struct Ftuple_L_Kchar_M_QDuration_Nfloat_20_3d_20_2e_2e_2e_M_QColor_Ncolor_20_3d_20_2e_2e_2e_R;
	struct Ftuple_L_Kchar_M_Kchar_R;
	struct Ftuple_L_Kchar_M_QColor_Ncolor_M_QDuration_Nfloat_R;
	struct Ftuple_Lany_Mability__component_R;
	struct Ftuple_Lagent_Mfloat_Mfloat_R;
	struct Ftuple_L_Kchar_M_QLevel_Nlog__level_20_3d_20_2e_2e_2e_R;
	struct Ftuple_Lnavigation__target_M_QReachRadius_Nfloat_20_3d_20_2e_2e_2e_M_QAllowPartialPath_Nlogic_20_3d_20_2e_2e_2e_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
	struct Ftuple_Lagent_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lfloat_Mfloat_R;
	struct Ftuple_Lfort__character_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lvector3_M_QParams_Nsphere__draw__params_20_3d_20_2e_2e_2e_R;
	struct Ftuple_Lvector3_Mfloat_Mfloat_R;
	struct Ftuple_Lvector3_Mvector3_R;
}

namespace Fortnite_Base_Head_Export_Skeleton_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace Fortnite_M_Avg_Player_AnimBlueprint
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace VerseAIBase_0
{
	struct Ftuple_Lnavigation__target_M_QReachRadius_Nfloat_20_3d_20_2e_2e_2e_M_QAllowPartialPath_Nlogic_20_3d_20_2e_2e_2e_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_Lfort__character_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_L_R;
	struct Ftuple_Lfort__item__descriptor_Mfort__item__tag_R;
	struct Ftuple_Lvector3_Mfloat_Mfloat_R;
	struct Ftuple_Lfort__inventory__item__asset_Mint_R;
	struct Ftuple_Lasset_M_Kchar_R;
	struct Ftuple_Lagent_Mfloat_Mfloat_R;
	struct Ftuple_Lagent_Mlogic_R;
}

namespace Burt_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace VerseDevices_0
{
	struct Ftuple_L_Kchar_M_QLevel_Nlog__level_20_3d_20_2e_2e_2e_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_Lrotation_Mrotation_R;
	struct Ftuple_L_R;
	struct Ftuple_L_Kchar_M_Kchar_R;
	struct Ftuple_Lvector3_Mvector3_R;
	struct Ftuple_Lvector3_Mrotation_R;
}

namespace Player_SourcePose_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace VerseCreature
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_Lnavigation__target_M_QReachRadius_Nfloat_20_3d_20_2e_2e_2e_M_QAllowPartialPath_Nlogic_20_3d_20_2e_2e_2e_R;
	struct Ftuple_L_R;
}

namespace B_MasterPetAnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace Player_FullBodyAimOffsets_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace Player_LowerBodyJog_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace B_AnimBP_HightowerRadish
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace HighTower_Tapas_Axe_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace Player_BuildingPose_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace SlidingLayerAnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace BoarRidingPlayerLayerAnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace F_MED_HIS_Ramirez_Head_01_Dyn_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}
